# Generated by Django 4.0.6 on 2023-05-12 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0002_remove_user_fullname_remove_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
