# Generated by Django 3.2.10 on 2023-04-13 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0002_auto_20230412_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester', models.TextField(blank=True, null=True)),
                ('amount', models.TextField(blank=True, null=True)),
                ('gateway', models.TextField(blank=True, null=True)),
                ('project', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
