# Generated by Django 3.2.10 on 2023-04-13 11:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0004_requests_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
