# Generated by Django 4.0.6 on 2023-05-17 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0006_remove_campaign_total_contributions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='target',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
