# Generated by Django 3.2.10 on 2023-04-15 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0011_requests_paykey'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributions',
            name='method',
            field=models.TextField(blank=True, null=True),
        ),
    ]
