# Generated by Django 3.2.10 on 2023-04-16 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0012_contributions_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributions',
            name='status',
            field=models.TextField(blank=True, default='pending', null=True),
        ),
    ]
