# Generated by Django 3.2.10 on 2023-04-17 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0013_contributions_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(blank=True, default='investor', max_length=20, null=True),
        ),
    ]
