# Generated by Django 3.2.10 on 2023-04-18 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0014_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='period',
            field=models.CharField(default='annually', max_length=200),
        ),
        migrations.AddField(
            model_name='campaign',
            name='roi',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
