# Generated by Django 3.2.10 on 2023-04-18 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0015_auto_20230418_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='roi',
            field=models.CharField(blank=True, default='3', max_length=20, null=True),
        ),
    ]
