# Generated by Django 3.2.10 on 2023-04-18 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0016_alter_campaign_roi'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributions',
            name='expected',
            field=models.TextField(default=0),
        ),
    ]
