# Generated by Django 3.2.10 on 2023-04-18 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0018_contributions_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributions',
            name='paidout',
            field=models.BooleanField(default=False),
        ),
    ]
