# Generated by Django 3.2.10 on 2023-04-25 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0019_contributions_paidout'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributions',
            name='checkoutid',
            field=models.TextField(blank=True, null=True),
        ),
    ]
